#!/bin/sh

# Heath Stewart - 08 April 2020

# This script runs a query against the maillog in order to find 
# recipients of mail from the provided address.
# It will create a log file, log.txt, with all of the entries in
# the maillog that match the query. Then it will grep and sed
# against log.txt to display the recipient email addresses.
# Finally storing the recipients in a file, email.txt.
# This is my preferred output for another utility that takes in email
# addresses.

# check to make sure we have at least 1 argument
# preferably this is the domain of the sender in question
[ $# -lt 1 ] && echo "Usage: mlp <from>" && exit 1

# store arg 1 as a var, and define other vars for later use
from=$1
out_file="/root/scripts/log.txt"
recip="/root/scripts/email.txt"
log="/var/log/maillog"

# grep the maillog for arg 1, then output that to the defined out_file
grep -i ${from} ${log} > ${out_file}

# store the actual email address in a var called culprit
culprit=`grep "from=<" ${out_file} | cut -d" " -f 8 | sed 's/from=<\(.*\)=//;s/>,//' | sort -u`

# display the output to the user, including the sender's address
# and all of the recipients addresses
echo "[ The following received mail from ${culprit} ]"
echo ""
grep "to=<" ${out_file} | cut -d" " -f 1,3,4,8 | sed 's/to=<//;s/>,//'
echo ""
echo "--> '~/scripts/email.txt' created with list of recipient addresses. Use this file for running shellphish.ps1"

# send the receipient addresses to a file
grep "to=<" ${out_file} | cut -d" " -f 8 | sed 's/to=<//;s/>,//' > ${recip}
